---
# $Author$
# $Date$
# $Source$

# Set up the Newrelic Infrastructure agent on a Redhat server from local files
- name: Copy newrelic-infra gpg key to the host
  copy:
    src: "{{ newrelic_infra_agent_source }}/el{{ ansible_distribution_major_version }}/newrelic-infra.gpg"
    dest: "/tmp/newrelic-infra.gpg"
    owner: root
    group: root
    mode: '0600'
  check_mode: false
  changed_when: false

- name: Remove agent repo keys if they exist
  rpm_key:
    key: /tmp/newrelic-infra.gpg
    state: absent
  ignore_errors: true
  notify: yum-clean-metadata

- name: Remove the temporary newrelic-infra gpg key
  file:
    name: /tmp/newrelic-infra.gpg
    state: absent
  check_mode: false
  changed_when: false

- name: Remove agent repo reference
  yum_repository:
    name: 'newrelic-infra'
    state: absent
  notify: yum-clean-metadata

- name: Display the newrelic-infra agent packages to be installed
  debug:
    msg: "{{ item.name }}-{{ item.version }}-{{ item.release }}.{{ ansible_architecture }}.rpm"
    verbosity: 2
  with_items:  "{{ newrelic_infra_packages }}"

- name: Copy newrelic-infra agent packages to the host
  copy:
    src: "{{ newrelic_infra_agent_source }}/el{{ ansible_distribution_major_version }}/{{ item.name }}-{{ item.version }}-{{ item.release }}.{{ ansible_architecture }}.rpm"
    dest: "/tmp/{{ item.name }}-{{ item.version }}-{{ item.release }}.{{ ansible_architecture }}.rpm"
    owner: root
    group: root
    mode: '0600'
  when:  item.state != "absent"
  with_items:  "{{ newrelic_infra_packages }}"
  check_mode: false
  changed_when: false

- name: Remove obsolete New Relic packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  when:  item.state == "absent"
  with_items:  "{{ newrelic_infra_packages }}"
  register: newrelic_install
  notify: Restart newrelic-infra

- name: Display the newrelic-infra agent removal results
  debug:
    var: newrelic_install
    verbosity: 2

- name: Install the newrelic-infra agent packages.
  package:
    name: "/tmp/{{ item.name }}-{{ item.version }}-{{ item.release }}.{{ ansible_architecture }}.rpm"
    state: "{{ item.state }}"
  when:  item.state != "absent"
  with_items:  "{{ newrelic_infra_packages }}"
  register: newrelic_install
  notify: Restart newrelic-infra

- name: Display the newrelic-infra agent installation results
  debug:
    var: newrelic_install
    verbosity: 2

- name: Remove the temporary newrelic-infra packages used for the install
  file:
    name: "/tmp/{{ item.name }}-{{ item.version }}-{{ item.release }}.{{ ansible_architecture }}.rpm"
    state: absent
  with_items:  "{{ newrelic_infra_packages }}"
  changed_when: "newrelic_install.changed"
  check_mode: false
