---
# $Author$
# $Date$
# $Source$


##############################################
# New Relic Infrastructure installation role #
##############################################

- name: Dump the variables / facts known by Ansible for the New Relic Infra role
  include_role:
    name: mdrotthoff.ansible-debug

#- name: Build the proxy URI required for the Yum repository if appropriate
#  set_fact:
#    newrelic_infra_repo_proxy: "{{ newrelic_infra_proxy_server }}:{{ newrelic_infra_proxy_port }}"
#  when:
#    - newrelic_infra_proxy_server is defined
#    - newrelic_infra_proxy_port is defined

- name: Configuration for the New Relic Yum repository
  yum_repository:
    name: newrelic_infra-agent
    description: New Relic Infrastructure
    baseurl: "{{ newrelic_infra_repo_baseurl }}"
    gpgcheck: "{{ newrelic_infra_repo_gpgcheck }}"
    repo_gpgcheck: "{{ newrelic_infra_repo_repo_gpgcheck }}"
    gpgkey: "{{ newrelic_infra_repo_gpgkey }}"
    proxy: "{{ newrelic_infra_repo_proxy | default(omit) }}"
    enabled: "{{ newrelic_infra_repo_enabled | default(True) }}"

- name: Copy the RPM GPG key locally for installation via proxy
  get_url:
    url: "{{ newrelic_infra_repo_gpgkey }}"
    dest: /tmp/newrelic-infra.gpg
    validate_certs: False
  changed_when: False
  environment:
    http_proxy: "{{ newrelic_infra_repo_proxy | default(omit) }}"
    https_proxy: "{{ newrelic_infra_repo_proxy | default(omit) }}"
  when:
    - newrelic_infra_repo_proxy is defined

- name: Copy the RPM GPG key locally for installation w/o proxy
  get_url:
    url: "{{ newrelic_infra_repo_gpgkey }}"
    dest: /tmp/newrelic-infra.gpg
    validate_certs: False
  changed_when: False
  when:
    - newrelic_infra_repo_proxy is not defined

- name: Install the RPM GPG key
  rpm_key:
    key: /tmp/newrelic-infra.gpg
    state: "{{ 'absent' if (newrelic_infra_package_state in ['absent', 'removed']) else 'present' }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Remove the downloaded RPM GPG key
  file:
    path: /tmp/newrelic-infra.gpg
    state: absent
  changed_when: False

#- name: Install the RPM GPG key
#  rpm_key:
#    key: "{{ newrelic_infra_repo_gpgkey }}"
#    state: "{{ 'absent' if (newrelic_infra_package_state in ['absent', 'removed']) else 'present' }}"

- name: Install the New Relic Infrastructure Agent package
  yum:
    name: "{{ newrelic_infra_package_name }}"
    state: "{{ newrelic_infra_package_state }}"
    enablerepo: newrelic_infra-agent
  notify:
    - Restart New Relic Agent
  ignore_errors: "{{ ansible_check_mode }}"

- name: Setup New Relic Infrastructure Agent Config file
  template:
    src: newrelic-infra.yml.j2
    dest: "{{ newrelic_infra_config_file }}"
  notify:
    - Restart New Relic Agent

- name: Install plugins for the New Relic Infrastructure Agent
  include_tasks: "{{ item }}.yml"
  loop: "{{ newrelic_infra_plugins }}"
  when:
    - newrelic_infra_plugins is defined

- name: Configure logrotate to ensure the New Relic Infrastructure Agent log files remain under control
  include_role:
    name: mdrotthoff.logrotate
  vars:
    logrotate_scripts:
      - name: newrelic_infra
        paths:
          - "{{ newrelic_infra_config_log_path }}/{{ newrelic_infra_config_log_file }}"
        options:
          - missingok
          - compress
          - delaycompress
          - notifempty

- name: Configure the New Relic Infrastructure service
  service:
    name: "{{ newrelic_infra_service_name }}"
    state: "{{ newrelic_infra_service_state }}"
    enabled: "{{ newrelic_infra_service_enabled }}"

