---
# $Author$
# $Date$
# $Source$

- name: Configuration for the New Relic Yum repository
  yum_repository:
    name: newrelic_infra_agent
    description: New Relic Infrastructure
    baseurl: "{{ newrelic_infra_repo_baseurl }}"
    gpgcheck: "{{ newrelic_infra_repo_gpgcheck }}"
    repo_gpgcheck: "{{ newrelic_infra_repo_repo_gpgcheck }}"
    gpgkey: "{{ newrelic_infra_repo_gpgkey }}"
    proxy: "{{ newrelic_infra_repo_proxy | default(omit) }}"
 
- name: Install the RPM GPG key
  rpm_key:
    key: "{{ newrelic_infra_repo_gpgkey }}"
    state: present

- name: Install the New Relic Infrastructure Agent package
  package:
    name: "{{ newrelic_infra_package }}"
    state: "{{ newrelic_infra_state }}"
  notify:
    - Restart New Relic Agent

- name: Setup New Relic Infrastructure Agent Config file
  template:
    src: newrelic-infra.conf.j2
    dest: "{{ newrelic_infra_config_file }}"
  notify:
    - Restart New Relic Agent

- name: Configure logrotate to ensure the New Relic Infrastructure Agent log files remain under control
  include_role:
    name: mdrotthoff.logrotate
  vars:
    logrotate_scripts:
      - name: newrelic_infra
        paths:
          - "{{ newrelic_infra_config_log_path }}/{{ newrelic_infra_config_log_file }}"
        options:
          - missingok
          - compress
          - delaycompress
          - notifempty
