---
# $Author$
# $Date$
# $Source$

- name: Install the New Relic Oracle DB plugin
  package:
    name: "{{ nri_oracledb_package }}"
    state: "{{ newrelic_infra_state }}"
  notify:
    - Restart New Relic Agent
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure the New Relic Oracle DB plugin
  template:
    src: nri-oracledb.yml.j2
    dest: "{{ nri_oracledb_config_file }}"
  notify:
    - Restart New Relic Agent
  when:
    - nri_oracledb_config is defined
    - nri_oracledb_config | length > 0
