---
# $Author$
# $Date$
# $Source$

- name: Install the New Relic Nagios plugin
  package:
    name: "{{ nri_nagios_package }}"
    state: "{{ newrelic_infra_state }}"
  notify:
    - Restart New Relic Agent
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install the supplemental packages required by the New Relic Nagios plugin
  package:
    name: "{{ nri_nagios_supplemental_packages }}"
    state: "{{ newrelic_infra_state }}"
  notify:
    - Restart New Relic Agent
  when:
    - nri_nagios_supplemental_packages is defined
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set up local Nagios checks on the New Relic server
  block:
    - name: Ensure the local Nagios checks directory exists
      file:
        path: "{{ nri_nagios_check_local_path }}"
        state: directory
        owner: "{{ nri_nagios_check_local_owner }}"
        group: "{{ nri_nagios_check_local_group }}"
        mode: "{{ nri_nagios_check_local_mode }}"

    - name: Copy the local check to the New Relic server
      copy:
        src: "{{ nri_nagios_check_local_src }}/{{ check_item }}"
        dest: "{{ nri_nagios_check_local_path }}/{{ check_item }}"
        owner: "{{ nri_nagios_check_local_owner }}"
        group: "{{ nri_nagios_check_local_group }}"
        mode: "{{ nri_nagios_check_local_mode }}"
      loop: "{{ nri_nagios_check_local }}"
      loop_control:
        loop_var: check_item
  when:
    - nri_nagios_check_local is defined
    - nri_nagios_check_local | length > 0
  
- name: Configure the New Relic Infrastructure Nagios plugin
  template:
    src: nri-nagios.yml.j2
    dest: "{{ nri_nagios_config_file }}"
  notify:
    - Restart New Relic Agent
  when:
    - nri_nagios_config is defined

- name: Configure the New Relic Infrastructure Nagios plugin service checks
  template:
    src: nri-nagios-service-checks.yml.j2
    dest: "{{ check_item.service_checks_config }}"
  loop: "{{ nri_nagios_config }}"
  loop_control:
    loop_var: check_item
  notify:
    - Restart New Relic Agent
  when:
    - nri_nagios_config is defined

