---
# $Author$
# $Date$
# $Source$

- name: Copy the local Nagios checks on the New Relic server
  block:
    - name: Build the local check on the New Relic server from a template
      template:
        src: "{{ nri_nagios_check_local_src }}/nagios_plugin_{{ check_item }}.j2"
        dest: "{{ nri_nagios_check_local_path }}/{{ check_item }}"
        owner: "{{ nri_nagios_check_local_owner }}"
        group: "{{ nri_nagios_check_local_group }}"
        mode: "{{ nri_nagios_check_local_mode }}"
  rescue:
    - name: Copy the local check file to the New Relic server
      copy:
        src: "{{ check_item }}"
        dest: "{{ nri_nagios_check_local_path }}/{{ check_item }}"
        owner: "{{ nri_nagios_check_local_owner }}"
        group: "{{ nri_nagios_check_local_group }}"
        mode: "{{ nri_nagios_check_local_mode }}"
