---
# $Author$
# $Date$
# $Source$

#- name: Display the value of the item variable
#  debug:
#    var: item
##    verbosity: "{{ debug_level | default(1) }}"

- name: Install the New Relic Elasticsearch plugin
  package:
    name: "{{ nri_elasticsearch_package }}"
    state: "{{ newrelic_infra_state }}"
  notify:
    - Restart New Relic Agent
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure the New Relic Infrastructure Elasticsearch plugin
  template:
    src: nri-elasticsearch.yml.j2
    dest: "{{ nri_elasticsearch_config_file }}"
    mode: 0600
  notify:
    - Restart New Relic Agent
  when:
    - nri_elasticsearch_config is defined
    - nri_elasticsearch_config | length > 0
