---
# $Author$
# $Date$
# $Source$

- name: Install the New Relic Oracle DB plugin
  package:
    name: "{{ nri_oracledb_package_name }}"
    state: "{{ nri_oracledb_package_state }}"
  notify:
    - Restart New Relic Agent
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install the supplemental packages required by the New Relic OracleDB plugin
  package:
    name: "{{ nri_oracledb_supplemental_packages }}"
    state: "{{ nri_oracledb_package_state }}"
  notify:
    - Restart New Relic Agent
  when:
    - nri_oracledb_supplemental_packages is defined 
    - not (nri_oracledb_package_state in [ "absent", "removed" ])
  ignore_errors: "{{ ansible_check_mode }}"

- name: Dump variable nri_oracledb_config
  debug:
    var: nri_oracledb_config
    verbosity: "{{ debug_level | default(1) }}"

- name: Configure the New Relic Oracle DB plugin
  template:
    src: nri-oracledb.yml.j2
    dest: "{{ nri_oracledb_config_file }}"
    mode: 0600
  notify:
    - Restart New Relic Agent
  when:
    - nri_oracledb_config is defined
    - nri_oracledb_config | length > 0
