---
# $Author$
# $Date$
# $Source$

- name: Install the New Relic Nagios plugin
  yum:
    name: "{{ nri_nagios_package_name }}"
    state: "{{ nri_nagios_package_state }}"
    enablerepo: newrelic_infra-agent
  notify:
    - Restart New Relic Agent
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install the supplemental packages required by the New Relic Nagios plugin
  yum:
    name: "{{ nri_nagios_supplemental_packages }}"
    state: "{{ nri_nagios_package_state }}"
  notify:
    - Restart New Relic Agent
  when:
    - nri_nagios_supplemental_packages is defined 
    - not (nri_nagios_package_state in [ "absent", "removed" ])
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set up local Nagios checks on the New Relic server
  block:
    - name: Ensure the local Nagios checks directory exists
      file:
        path: "{{ nri_nagios_check_local_path }}"
        state: directory
        owner: "{{ nri_nagios_check_local_owner }}"
        group: "{{ nri_nagios_check_local_group }}"
        mode: "{{ nri_nagios_check_local_mode }}"

    - name: Copy the local check to the New Relic server
      include_tasks: nri-nagios-local-check.yml
      loop: "{{ nri_nagios_check_local }}"
      loop_control:
        loop_var: check_item
  when:
    - nri_nagios_check_local is defined
    - nri_nagios_check_local | length > 0
  
- name: Configure the New Relic Infrastructure Nagios plugin
  template:
    src: nri-nagios.yml.j2
    dest: "{{ nri_nagios_config_file }}"
    mode: 0600
  notify:
    - Restart New Relic Agent
  when:
    - nri_nagios_config is defined

- name: Configure the New Relic Infrastructure Nagios plugin service checks
  template:
    src: nri-nagios-service-checks.yml.j2
    dest: "{{ check_item.service_checks_config }}"
    mode: 0600
  loop: "{{ nri_nagios_config }}"
  loop_control:
    loop_var: check_item
  notify:
    - Restart New Relic Agent
  when:
    - nri_nagios_config is defined

